# Generated by Django 5.2 on 2025-04-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=50, unique=True, verbose_name='Identificación (NIT, RUT, CUIT, etc.)')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('moneda', models.CharField(max_length=10, verbose_name='Moneda (Símbolo o Código)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
