# Generated by Django 5.2 on 2025-05-03 22:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_empresa_options_alter_empresa_actualizado_por_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("free", "Gratuito"),
                            ("pro", "Profesional"),
                            ("enterprise", "Empresarial"),
                        ],
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Identificador Plan",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Plan"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "limite_empresas",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Límite de Empresas"
                    ),
                ),
                (
                    "limite_usuarios",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Límite de Usuarios por Empresa"
                    ),
                ),
                (
                    "permite_aging_report",
                    models.BooleanField(
                        default=False, verbose_name="Permite Aging Report"
                    ),
                ),
                (
                    "permite_alertas",
                    models.BooleanField(default=False, verbose_name="Permite Alertas"),
                ),
                (
                    "permite_simulaciones_avanzadas",
                    models.BooleanField(
                        default=False, verbose_name="Permite Simulaciones Avanzadas"
                    ),
                ),
                (
                    "permite_importacion_frontend",
                    models.BooleanField(
                        default=False, verbose_name="Permite Importación Frontend"
                    ),
                ),
                (
                    "permite_api",
                    models.BooleanField(
                        default=False, verbose_name="Permite Acceso API"
                    ),
                ),
                (
                    "soporte_prioritario",
                    models.BooleanField(
                        default=False, verbose_name="Soporte Prioritario"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="¿Plan Disponible?"),
                ),
            ],
            options={
                "verbose_name": "Plan de Suscripción",
                "verbose_name_plural": "Planes de Suscripción",
                "ordering": ["limite_empresas", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="SuscripcionEmpresa",
            fields=[
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="suscripcion",
                        serialize=False,
                        to="core.empresa",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha Inicio Suscripción",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha Fin Suscripción (si aplica)",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True, verbose_name="¿Suscripción Activa?"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suscripciones",
                        to="core.plan",
                        verbose_name="Plan Asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción de Empresa",
                "verbose_name_plural": "Suscripciones de Empresas",
                "ordering": ["empresa__razon_social"],
            },
        ),
    ]
