# Generated by Django 5.2 on 2025-04-25 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=50, unique=True, verbose_name='Identificación (NIT, RUT, CUIT, etc.)')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='País')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_concepto', models.CharField(blank=True, max_length=150, verbose_name='Grupo o Concepto General')),
                ('pais_cobro', models.CharField(blank=True, max_length=100, verbose_name='País del Cobro')),
                ('fecha_factura', models.DateField(verbose_name='Fecha Factura/Contrato/OC')),
                ('numero_documento', models.CharField(help_text='Número único del documento emitido', max_length=100, verbose_name='Nº Factura/Documento')),
                ('producto_vendido_desc', models.TextField(blank=True, verbose_name='Descripción Productos/Servicios')),
                ('tipo_venta', models.CharField(choices=[('PROD', 'Venta de Producto'), ('SERV', 'Prestación de Servicio'), ('MIXT', 'Mixto (Producto y Servicio)'), ('OTRO', 'Otro')], default='PROD', max_length=4, verbose_name='Tipo de Venta')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Subtotal')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Impuestos')),
                ('total_factura', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15, verbose_name='Total Factura')),
                ('numero_cuotas', models.PositiveSmallIntegerField(default=1, help_text='Máximo 12', verbose_name='Número de Cuotas')),
                ('fecha_vencimiento_inicial', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento (Inicial)')),
                ('fecha_ultimo_seguimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Último Seguimiento')),
                ('estatus', models.CharField(choices=[('PEND', 'Pendiente'), ('PARC', 'Pagado Parcialmente'), ('PAGA', 'Pagado Totalmente'), ('VENC', 'Vencido'), ('ANUL', 'Anulado')], default='PEND', max_length=4, verbose_name='Estatus General')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios / Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='gestion.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('responsable_seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_en_seguimiento', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de Seguimiento')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Registro de Cobro',
                'verbose_name_plural': 'Registros de Cobros',
                'ordering': ['-fecha_factura', 'numero_documento'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCuotaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveSmallIntegerField(verbose_name='Nº Cuota')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto de la Cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('fecha_pago_real', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Pago')),
                ('estatus', models.CharField(choices=[('PEND', 'Pendiente'), ('PAGA', 'Pagada'), ('VENC', 'Vencida'), ('ANUL', 'Anulada')], default='PEND', max_length=4, verbose_name='Estatus Cuota')),
                ('observaciones_cuota', models.TextField(blank=True, verbose_name='Observaciones Específicas de la Cuota')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='gestion.cobro', verbose_name='Cobro Asociado')),
            ],
            options={
                'verbose_name': 'Detalle de Cuota de Cobro',
                'verbose_name_plural': 'Detalles de Cuotas de Cobros',
                'ordering': ['cobro', 'numero_cuota'],
            },
        ),
        migrations.AddIndex(
            model_name='cobro',
            index=models.Index(fields=['cliente'], name='gestion_cob_cliente_2b63d5_idx'),
        ),
        migrations.AddIndex(
            model_name='cobro',
            index=models.Index(fields=['fecha_factura'], name='gestion_cob_fecha_f_96c487_idx'),
        ),
        migrations.AddIndex(
            model_name='cobro',
            index=models.Index(fields=['estatus'], name='gestion_cob_estatus_cbfb85_idx'),
        ),
        migrations.AddIndex(
            model_name='detallecuotacobro',
            index=models.Index(fields=['cobro'], name='gestion_det_cobro_i_602034_idx'),
        ),
        migrations.AddIndex(
            model_name='detallecuotacobro',
            index=models.Index(fields=['fecha_vencimiento'], name='gestion_det_fecha_v_fd5f35_idx'),
        ),
        migrations.AddIndex(
            model_name='detallecuotacobro',
            index=models.Index(fields=['estatus'], name='gestion_det_estatus_d53f2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detallecuotacobro',
            unique_together={('cobro', 'numero_cuota')},
        ),
    ]
