# Generated by Django 5.2 on 2025-04-25 03:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_gastorecurrente_proveedor_pago_ocurrenciagasto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=150, verbose_name='Nombre del Banco')),
                ('numero_cuenta', models.CharField(max_length=100, unique=True, verbose_name='Número de Cuenta / Alias')),
                ('moneda', models.CharField(default='USD', max_length=10, verbose_name='Moneda Cuenta')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Saldo Actual')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro Cuenta')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Fecha Última Actualización Saldo')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_bancarias_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Último en Actualizar Saldo')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_bancarias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['nombre_banco', 'numero_cuenta'],
            },
        ),
        migrations.CreateModel(
            name='VentaProyectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_concepto', models.CharField(blank=True, max_length=150, verbose_name='Grupo o Concepto de la Venta')),
                ('codigo_oportunidad', models.CharField(blank=True, help_text='Código único si aplica', max_length=50, null=True, unique=True, verbose_name='Código Oportunidad')),
                ('estatus', models.CharField(choices=[('PROS', 'Prospecto'), ('CALI', 'Calificado'), ('PROP', 'Propuesta Enviada'), ('NEGO', 'En Negociación'), ('GANA', 'Ganada (Pendiente Facturar)'), ('PERD', 'Perdida'), ('APLA', 'Aplazada')], default='PROS', max_length=4, verbose_name='Estatus')),
                ('pais_venta', models.CharField(blank=True, max_length=100, verbose_name='País de la Venta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la Venta')),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Total Estimado')),
                ('porcentaje_margen', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor entre 0 y 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Margen Estimado')),
                ('margen_estimado', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15, verbose_name='Margen Estimado ($)')),
                ('fecha_cierre_estimada', models.DateField(verbose_name='Fecha Estimada de Cierre')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios / Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_proyectadas_actualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('asesor_comercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asesor Comercial')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_proyectadas', to='gestion.cliente', verbose_name='Cliente Potencial')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_proyectadas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('responsable_seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyecciones_en_seguimiento', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Seguimiento')),
            ],
            options={
                'verbose_name': 'Venta Proyectada / Oportunidad',
                'verbose_name_plural': 'Ventas Proyectadas / Oportunidades',
                'ordering': ['fecha_cierre_estimada', 'estatus'],
                'indexes': [models.Index(fields=['cliente'], name='gestion_ven_cliente_055b88_idx'), models.Index(fields=['fecha_cierre_estimada'], name='gestion_ven_fecha_c_76eb90_idx'), models.Index(fields=['estatus'], name='gestion_ven_estatus_653186_idx'), models.Index(fields=['asesor_comercial'], name='gestion_ven_asesor__832bd2_idx')],
            },
        ),
    ]
