# Generated by Django 5.2 on 2025-04-27 03:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_cobro_adjunto_factura_cobro_venta_proyectada_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecuotacobro',
            name='cuenta_bancaria_deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos_recibidos', to='gestion.cuentabancaria', verbose_name='Cuenta Bancaria Depósito'),
        ),
        migrations.AddField(
            model_name='detallecuotacobro',
            name='numero_retencion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nº Retención Fiscal'),
        ),
        migrations.AddField(
            model_name='detallecuotacobro',
            name='valor_retencion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Retención Fiscal'),
        ),
    ]
