# Generated by Django 5.2 on 2025-04-27 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_detallecuotacobro_cuenta_bancaria_deposito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Contacto')),
                ('cargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('telefono_directo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Directo')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular / Móvil')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿Es Contacto Principal?')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='gestion.cliente')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='gestion.proveedor')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['cliente', 'proveedor', '-es_principal', 'nombre'],
            },
        ),
    ]
